config/routes.rb
Simei::Application.routes.draw do
  resources :pcorps

   match ':controller(/:action(/:id(.:format)))'
end

app/models/pcorp.rb
# coding: utf-8
class Pcorp < ActiveRecord::Base
  # scope :name, where('reno like ? AND cname like ?', '%'+params[:reno].tr('０-９','0-9')+'%', '%'+params[:cname]+'%').order('reno ASC')
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pcorps_controller.rb
class PcorpsController < ApplicationController
  # GET /pcorps
  # GET /pcorps.xml
  def index
   #@pcorps = Pcorp.all
    @pcorps = Pcorp.order('reno ASC')
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pcorps }
    end
  end

  # GET /pcorps/1
  # GET /pcorps/1.xml
  def show
    @pcorp = Pcorp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pcorp }
    end
  end

  # GET /pcorps/new
  # GET /pcorps/new.xml
  def new
    @pcorp = Pcorp.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pcorp }
    end
  end

  # GET /pcorps/1/edit
  def edit
    @pcorp = Pcorp.find(params[:id])
  end

  # POST /pcorps
  # POST /pcorps.xml
  def create
    @pcorp = Pcorp.new(params[:pcorp])

    respond_to do |format|
      if @pcorp.save
        format.html { redirect_to(@pcorp, :notice => 'Pcorp was successfully created.') }
        format.xml  { render :xml => @pcorp, :status => :created, :location => @pcorp }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pcorp.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pcorps/1
  # PUT /pcorps/1.xml
  def update
    @pcorp = Pcorp.find(params[:id])

    respond_to do |format|
      if @pcorp.update_attributes(params[:pcorp])
        format.html { redirect_to(@pcorp, :notice => 'Pcorp was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pcorp.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pcorps/1
  # DELETE /pcorps/1.xml
  def destroy
    @pcorp = Pcorp.find(params[:id])
    @pcorp.destroy

    respond_to do |format|
      format.html { redirect_to(pcorps_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/record_controller.rb
# -*- encoding: utf-8 -*-

class RecordController < ApplicationController
  def ph1
    # 登録番号と名前で検索
    # @pcorps = Pcorp.find(:all, :conditions => ['reno LIKE ?', 'cname LIKE ?', '%'+params[:reno]+'%', '%'+params[:cname])+'%'])
    @pcorps = Pcorp.where('reno like ? AND cname like ?', '%'+params[:reno].tr('０-９','0-9')+'%', '%'+params[:cname]+'%').order('reno ASC')
    # @pcorps = Pcorp.name
    # respond_to do |format|
    #  format.html # index.html.reb
    #  format.xml{ render :xml => @pcorps}
    # end
    render 'pcorps/index'
  end

  def ph2
    # 希望職種で検索
    @pcorps = Pcorp.where('wbu = ? OR wco = ? OR wgs = ?', params[:wbu], params[:wco], params[:wgs]).order('reno ASC')
    render 'pcorps/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pcorps_helper.rb
module PcorpsHelper
end

app/helpers/record_helper.rb
module RecordHelper
end

app/views/layouts/application.html-bu.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simei</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>須恵町指名業者登録</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pcorps/_form.html.erb
<%= form_for(@pcorp) do |f| %>
  <% if @pcorp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pcorp.errors.count, "error") %> prohibited this pcorp from being saved:</h2>

      <ul>
      <% @pcorp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reno %><br />
    <%= f.text_field :reno %>
  </div>
  <div class="field">
    <%= f.label :cnamek %><br />
    <%= f.text_field :cnamek %>
  </div>
  <div class="field">
    <%= f.label :cname %><br />
    <%= f.text_field :cname %>
  </div>
  <div class="field">
    <%= f.label :posi %><br />
    <%= f.text_field :posi %>
  </div>
  <div class="field">
    <%= f.label :repk %><br />
    <%= f.text_field :repk %>
  </div>
  <div class="field">
    <%= f.label :rep %><br />
    <%= f.text_field :rep %>
  </div>
  <div class="field">
    <%= f.label :bd %><br />
    <%= f.date_select :bd %>
  </div>
  <div class="field">
    <%= f.label :ad %><br />
    <%= f.text_field :ad %>
  </div>
  <div class="field">
    <%= f.label :tel %><br />
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :fax %><br />
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :eml %><br />
    <%= f.text_field :eml %>
  </div>
  <div class="field">
    <%= f.label :cap %><br />
    <%= f.text_field :cap %>
  </div>
  <div class="field">
    <%= f.label :cy %><br />
    <%= f.text_field :cy %>
  </div>
  <div class="field">
    <%= f.label :emp %><br />
    <%= f.text_field :emp %>
  </div>
  <div class="field">
    <%= f.label :acc %><br />
    <%= f.date_select :acc %>
  </div>
  <div class="field">
    <%= f.label :md %><br />
    <%= f.check_box :md %>
  </div>
  <div class="field">
    <%= f.label :wbu %><br />
    <%= f.check_box :wbu %>
  </div>
  <div class="field">
    <%= f.label :wco %><br />
    <%= f.check_box :wco %>
  </div>
  <div class="field">
    <%= f.label :wgs %><br />
    <%= f.check_box :wgs %>
  </div>
  <div class="field">
    <%= f.label :io %><br />
    <%= f.check_box :io %>
  </div>
  <div class="field">
    <%= f.label :ban %><br />
    <%= f.check_box :ban %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :bno %><br />
    <%= f.text_field :bno %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pcorps/edit.html.erb
<h1>Editing pcorp</h1>

<%= render 'form' %>

<%= link_to 'Show', @pcorp %> |
<%= link_to 'Back', pcorps_path %>

app/views/pcorps/index.html.erb
<h1>登録業者一覧</h1>
<%= link_to '再検索', { :controller => 'record', :action => 'keyword' } %>
<table>
  <tr>
    <th>受付番号</th>
<!--     <th>商号又は名称カナ</th> -->
    <th>商号又は名称</th>
    <th>代表者役職名</th>
<!--     <th>代表者名カナ</th> -->
    <th>代表者名</th>
<!--     <th>生年月日</th> -->
    <th>住所</th>
    <th>TEL</th>
    <th>FAX</th>
<!--    <th>Eml</th> -->
<!--     <th>自己資本額（千円）</th> -->
<!--     <th>営業年数</th> -->
<!--     <th>総職員数</th> -->
<!--     <th>決算日（直近）</th> -->
<!--     <th>受託</th> -->
<!--     <th>希望：建設</th> -->
<!--     <th>希望：コンサル</th> -->
<!--     <th>希望：物品</th> -->
<!--     <th>町外区分</th> -->
<!--     <th>指名停止</th> -->
<!--     <th>備考</th> -->
<!--     <th>BOX番号</th> -->
    <th></th>
    <th></th>
    <th></th>
  <hr size="1" >
  </tr>

<% @pcorps.each do |pcorp| %>
  <tr style="background-color:<%= cycle('#FFFFFF', '#F5F5F5') %>">
    <td><%= pcorp.reno %></td>
<!--     <td><%= pcorp.cnamek %></td> -->
    <td><%= pcorp.cname %></td>
    <td><%= pcorp.posi %></td>
<!--     <td><%= pcorp.repk %></td> -->
    <td><%= pcorp.rep %></td>
<!--     <td><%= pcorp.bd %></td> -->
    <td><%= pcorp.ad %></td>
    <td><%= pcorp.tel %></td>
    <td><%= pcorp.fax %></td>
<!--     <td><%= pcorp.eml %></td> -->
<!--     <td><%= pcorp.cap %></td> -->
<!--     <td><%= pcorp.cy %></td> -->
<!--     <td><%= pcorp.emp %></td> -->
<!--     <td><%= pcorp.acc %></td> -->
<!--     <td><%= pcorp.md %></td> -->
<!--     <td><%= pcorp.wbu %></td> -->
<!--     <td><%= pcorp.wco %></td> -->
<!--     <td><%= pcorp.wgs %></td> -->
<!--     <td><%= pcorp.io %></td> -->
<!--     <td><%= pcorp.ban %></td> -->
<!--     <td><%= pcorp.note %></td> -->
<!--     <td><%= pcorp.bno %></td> -->
    <td><%= link_to '詳細', pcorp %></td>
<!--    <td><%= link_to 'Edit', edit_pcorp_path(pcorp) %></td> -->
<!--    <td><%= link_to 'Destroy', pcorp, :confirm => 'Are you sure?', :method => :delete %></td> -->
  </tr>
<% end %>
</table>

<br />

<!-- <%= link_to 'New Pcorp', new_pcorp_path %> -->

app/views/pcorps/index_b.html.erb
<h1>Listing pcorps</h1>

<table>
  <tr>
    <th>Reno</th>
    <th>Cnamek</th>
    <th>Cname</th>
    <th>Posi</th>
    <th>Repk</th>
    <th>Rep</th>
    <th>Bd</th>
    <th>Ad</th>
    <th>Tel</th>
    <th>Fax</th>
    <th>Eml</th>
    <th>Cap</th>
    <th>Cy</th>
    <th>Emp</th>
    <th>Acc</th>
    <th>Md</th>
    <th>Wbu</th>
    <th>Wco</th>
    <th>Wgs</th>
    <th>Io</th>
    <th>Ban</th>
    <th>Note</th>
    <th>Bno</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pcorps.each do |pcorp| %>
  <tr>
    <td><%= pcorp.reno %></td>
    <td><%= pcorp.cnamek %></td>
    <td><%= pcorp.cname %></td>
    <td><%= pcorp.posi %></td>
    <td><%= pcorp.repk %></td>
    <td><%= pcorp.rep %></td>
    <td><%= pcorp.bd %></td>
    <td><%= pcorp.ad %></td>
    <td><%= pcorp.tel %></td>
    <td><%= pcorp.fax %></td>
    <td><%= pcorp.eml %></td>
    <td><%= pcorp.cap %></td>
    <td><%= pcorp.cy %></td>
    <td><%= pcorp.emp %></td>
    <td><%= pcorp.acc %></td>
    <td><%= pcorp.md %></td>
    <td><%= pcorp.wbu %></td>
    <td><%= pcorp.wco %></td>
    <td><%= pcorp.wgs %></td>
    <td><%= pcorp.io %></td>
    <td><%= pcorp.ban %></td>
    <td><%= pcorp.note %></td>
    <td><%= pcorp.bno %></td>
    <td><%= link_to 'Show', pcorp %></td>
    <td><%= link_to 'Edit', edit_pcorp_path(pcorp) %></td>
    <td><%= link_to 'Destroy', pcorp, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pcorp', new_pcorp_path %>

app/views/pcorps/new.html.erb
<h1>New pcorp</h1>

<%= render 'form' %>

<%= link_to 'Back', pcorps_path %>

app/views/pcorps/show.html.erb
<p id="notice"><%= notice %></p>
| <%= link_to '戻る', '/index.html' %>

<p>
  <b>受付番号:</b>
  <%= @pcorp.reno %>
</p>

<p>
  <b>商号名称カナ:</b>
  <%= @pcorp.cnamek %>
</p>

<p>
  <b>商号名称:</b>
  <%= @pcorp.cname %>
</p>

<p>
  <b>役職名:</b>
  <%= @pcorp.posi %>
</p>

<p>
  <b>代表者カナ:</b>
  <%= @pcorp.repk %>
</p>

<p>
  <b>代表者:</b>
  <%= @pcorp.rep %>
</p>

<p>
  <b>生年月日:</b>
  <%= @pcorp.bd %>
</p>

<p>
  <b>住所:</b>
  <%= @pcorp.ad %>
</p>

<p>
  <b>Tel:</b>
  <%= @pcorp.tel %>
</p>

<p>
  <b>Fax:</b>
  <%= @pcorp.fax %>
</p>

<p>
  <b>Email:</b>
  <%= @pcorp.eml %>
</p>

<p>
  <b>自己資本額（千円）:</b>
  <%= @pcorp.cap %>
</p>

<p>
  <b>営業年数:</b>
  <%= @pcorp.cy %>
</p>

<p>
  <b>総職員数:</b>
  <%= @pcorp.emp %>
</p>

<p>
  <b>決算日:</b>
  <%= @pcorp.acc %>
</p>

<p>
  <b>受任有無:</b>
  <%= @pcorp.md %>
</p>

<p>
  <b>希望業種（建設）:</b>
  <%= @pcorp.wbu %>
</p>

<p>
  <b>希望業種（コンサル）:</b>
  <%= @pcorp.wco %>
</p>

<p>
  <b>希望業種（物品）:</b>
  <%= @pcorp.wgs %>
</p>

<p>
  <b>町外区分:</b>
  <%= @pcorp.io %>
</p>

<p>
  <b>指名停止:</b>
  <%= @pcorp.ban %>
</p>

<p>
  <b>備考:</b>
  <%= @pcorp.note %>
</p>

<p>
  <b>ボックス番号:</b>
  <%= @pcorp.bno %>
</p>

<!--   <%= link_to 'Edit', edit_pcorp_path(@pcorp) %>   --> |
<!--  <%= link_to '戻る', pcorps_path %>  -->
<%= link_to '戻る', '/index.html' %>

app/views/record/keyword.html.erb
<%= form_tag :action => 'ph1' do %>
  <div class="field">
    <%= label_tag 'reno', '受付番号' %><br />
    <%= text_field_tag 'reno' %>
  </div>
  <div class="field">
    <%= label_tag 'cname', '商号または名称' %><br />
    <%= text_field_tag 'cname' %>
  </div>
    <%= submit_tag '検索' %>
<% end %>　

app/views/record/keyword2.html.erb
<%= form_tag :action => 'ph2' do %>
  <div class="field">
    <%= label_tag 'wbu', '希望業種（建設）' %><br />
    <%= check_box_tag 'wbu' %>
  </div>
  <div class="field">
    <%= label_tag 'wco', '希望業種（コンサル）' %><br />
    <%= check_box_tag 'wco' %>
  </div>
  <div class="field">
    <%= label_tag 'wbu', '希望業種（物品）' %><br />
    <%= check_box_tag 'wgs' %>
  </div>
    <%= submit_tag '検索' %>
<% end %>　